function Z_ori = originalpolynominal(X_fit, Y_fit, cond)
    % 入力:
    % X_fit, Y_fit: 入力データのメッシュグリッド
    % cond: 導電助剤の電子伝導率
    % 出力:
    % Z_ori: 元の多項式で評価された z の値
    
    % Z_ori を計算
    Z_ori = cond * ( ...
        0.022 * Y_fit.^0 + ...
        31 * Y_fit.^1 - ...
        4.7 * Y_fit.^2 - ...
        46 * Y_fit.^3 + ...
        43 * Y_fit.^4 - ...
        21 * Y_fit.^5);
end